# Exercise for Classification

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv ("data/credit-g.csv", na_values="?")
df

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,'<0',6,'critical/other existing credit',radio/tv,1169,'no known savings','>=7',4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,'0<=X<200',48,'existing paid',radio/tv,5951,'<100','1<=X<4',2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,'<100','4<=X<7',2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,'<0',42,'existing paid',furniture/equipment,7882,'<100','4<=X<7',2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,'<0',24,'delayed previously','new car',4870,'<100','1<=X<4',3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
5,'no checking',36,'existing paid',education,9055,'no known savings','1<=X<4',2,'male single',none,...,'no known property',35,none,'for free',1,'unskilled resident',2,yes,yes,good
6,'no checking',24,'existing paid',furniture/equipment,2835,'500<=X<1000','>=7',3,'male single',none,...,'life insurance',53,none,own,1,skilled,1,none,yes,good
7,'0<=X<200',36,'existing paid','used car',6948,'<100','1<=X<4',2,'male single',none,...,car,35,none,rent,1,'high qualif/self emp/mgmt',1,yes,yes,good
8,'no checking',12,'existing paid',radio/tv,3059,'>=1000','4<=X<7',2,'male div/sep',none,...,'real estate',61,none,own,1,'unskilled resident',1,none,yes,good
9,'0<=X<200',30,'critical/other existing credit','new car',5234,'<100',unemployed,4,'male mar/wid',none,...,car,28,none,own,2,'high qualif/self emp/mgmt',1,none,yes,bad
10,'0<=X<200',12,'existing paid','new car',1295,'<100','<1',3,'female div/dep/mar',none,...,car,25,none,rent,1,skilled,1,none,yes,bad
11,'<0',48,'existing paid',business,4308,'<100','<1',3,'female div/dep/mar',none,...,'life insurance',24,none,rent,1,skilled,1,none,yes,bad
12,'0<=X<200',12,'existing paid',radio/tv,1567,'<100','1<=X<4',1,'female div/dep/mar',none,...,car,22,none,own,1,skilled,1,yes,yes,good
13,'<0',24,'critical/other existing credit','new car',1199,'<100','>=7',4,'male single',none,...,car,60,none,own,2,'unskilled resident',1,none,yes,bad
14,'<0',15,'existing paid','new car',1403,'<100','1<=X<4',2,'female div/dep/mar',none,...,car,28,none,rent,1,skilled,1,none,yes,good
15,'<0',24,'existing paid',radio/tv,1282,'100<=X<500','1<=X<4',4,'female div/dep/mar',none,...,car,32,none,own,1,'unskilled resident',1,none,yes,bad
16,'no checking',24,'critical/other existing credit',radio/tv,2424,'no known savings','>=7',4,'male single',none,...,'life insurance',53,none,own,2,skilled,1,none,yes,good
17,'<0',30,'no credits/all paid',business,8072,'no known savings','<1',2,'male single',none,...,car,25,bank,own,3,skilled,1,none,yes,good
18,'0<=X<200',24,'existing paid','used car',12579,'<100','>=7',4,'female div/dep/mar',none,...,'no known property',44,none,'for free',1,'high qualif/self emp/mgmt',1,yes,yes,bad
19,'no checking',24,'existing paid',radio/tv,3430,'500<=X<1000','>=7',3,'male single',none,...,car,31,none,own,1,skilled,2,yes,yes,good
20,'no checking',9,'critical/other existing credit','new car',2134,'<100','1<=X<4',4,'male single',none,...,car,48,none,own,3,skilled,1,yes,yes,good
21,'<0',6,'existing paid',radio/tv,2647,'500<=X<1000','1<=X<4',2,'male single',none,...,'real estate',44,none,rent,1,skilled,2,none,yes,good
22,'<0',10,'critical/other existing credit','new car',2241,'<100','<1',1,'male single',none,...,'real estate',48,none,rent,2,'unskilled resident',2,none,no,good
23,'0<=X<200',12,'critical/other existing credit','used car',1804,'100<=X<500','<1',3,'male single',none,...,'life insurance',44,none,own,1,skilled,1,none,yes,good
24,'no checking',10,'critical/other existing credit',furniture/equipment,2069,'no known savings','1<=X<4',2,'male mar/wid',none,...,car,26,none,own,2,skilled,1,none,no,good
25,'<0',6,'existing paid',furniture/equipment,1374,'<100','1<=X<4',1,'male single',none,...,'real estate',36,bank,own,1,'unskilled resident',1,yes,yes,good
26,'no checking',6,'no credits/all paid',radio/tv,426,'<100','>=7',4,'male mar/wid',none,...,car,39,none,own,1,'unskilled resident',1,none,yes,good
27,'>=200',12,'all paid',radio/tv,409,'>=1000','1<=X<4',3,'female div/dep/mar',none,...,'real estate',42,none,rent,2,skilled,1,none,yes,good
28,'0<=X<200',7,'existing paid',radio/tv,2415,'<100','1<=X<4',3,'male single',guarantor,...,'real estate',34,none,own,1,skilled,1,none,yes,good
29,'<0',60,'delayed previously',business,6836,'<100','>=7',3,'male single',none,...,'no known property',63,none,own,2,skilled,1,yes,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,'0<=X<200',15,'existing paid',repairs,1514,'100<=X<500','1<=X<4',4,'male single',guarantor,...,'real estate',22,none,own,1,skilled,1,none,yes,good
971,'no checking',24,'existing paid','new car',7393,'<100','1<=X<4',1,'male single',none,...,'life insurance',43,none,own,1,'unskilled resident',2,none,yes,good
972,'<0',24,'all paid','new car',1193,'<100',unemployed,1,'female div/dep/mar','co applicant',...,'no known property',29,none,rent,2,'unemp/unskilled non res',1,none,yes,bad
973,'<0',60,'existing paid',business,7297,'<100','>=7',4,'male single','co applicant',...,'no known property',36,none,rent,1,skilled,1,none,yes,bad
974,'no checking',30,'critical/other existing credit',radio/tv,2831,'<100','1<=X<4',4,'female div/dep/mar',none,...,car,33,none,own,1,skilled,1,yes,yes,good
975,'>=200',24,'existing paid',radio/tv,1258,'500<=X<1000','1<=X<4',3,'female div/dep/mar',none,...,car,57,none,own,1,'unskilled resident',1,none,yes,good
976,'0<=X<200',6,'existing paid',radio/tv,753,'<100','1<=X<4',2,'female div/dep/mar',guarantor,...,'real estate',64,none,own,1,skilled,1,none,yes,good
977,'0<=X<200',18,'delayed previously',business,2427,'no known savings','>=7',4,'male single',none,...,'life insurance',42,none,own,2,skilled,1,none,yes,good
978,'no checking',24,'delayed previously','new car',2538,'<100','>=7',4,'male single',none,...,car,47,none,own,2,'unskilled resident',2,none,yes,bad
979,'0<=X<200',15,'all paid','new car',1264,'100<=X<500','1<=X<4',2,'male mar/wid',none,...,'life insurance',25,none,rent,1,skilled,1,none,yes,bad
980,'0<=X<200',30,'critical/other existing credit',furniture/equipment,8386,'<100','4<=X<7',2,'male single',none,...,'life insurance',49,none,own,1,skilled,1,none,yes,bad
981,'no checking',48,'existing paid',business,4844,'<100',unemployed,3,'male single',none,...,car,33,bank,rent,1,'high qualif/self emp/mgmt',1,yes,yes,bad
982,'>=200',21,'existing paid','new car',2923,'100<=X<500','1<=X<4',1,'female div/dep/mar',none,...,car,28,bank,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
983,'<0',36,'existing paid','used car',8229,'<100','1<=X<4',2,'male single',none,...,'life insurance',26,none,own,1,skilled,2,none,yes,bad
984,'no checking',24,'critical/other existing credit',furniture/equipment,2028,'<100','4<=X<7',2,'male single',none,...,'life insurance',30,none,own,2,'unskilled resident',1,none,yes,good
985,'<0',15,'critical/other existing credit',furniture/equipment,1433,'<100','1<=X<4',4,'female div/dep/mar',none,...,'life insurance',25,none,rent,2,skilled,1,none,yes,good
986,'>=200',42,'no credits/all paid',business,6289,'<100','<1',2,'male div/sep',none,...,'life insurance',33,none,own,2,skilled,1,none,yes,good
987,'no checking',13,'existing paid',radio/tv,1409,'100<=X<500',unemployed,2,'female div/dep/mar',none,...,'real estate',64,none,own,1,skilled,1,none,yes,good
988,'<0',24,'existing paid','used car',6579,'<100',unemployed,4,'male single',none,...,'no known property',29,none,'for free',1,'high qualif/self emp/mgmt',1,yes,yes,good
989,'0<=X<200',24,'critical/other existing credit',radio/tv,1743,'<100','>=7',4,'male single',none,...,'life insurance',48,none,own,2,'unskilled resident',1,none,yes,good
990,'no checking',12,'critical/other existing credit',education,3565,'no known savings','<1',2,'male single',none,...,'life insurance',37,none,own,2,'unskilled resident',2,none,yes,good
991,'no checking',15,'all paid',radio/tv,1569,'100<=X<500','>=7',4,'male single',none,...,car,34,bank,own,1,'unskilled resident',2,none,yes,good
992,'<0',18,'existing paid',radio/tv,1936,'no known savings','4<=X<7',2,'male mar/wid',none,...,car,23,none,rent,2,'unskilled resident',1,none,yes,good
993,'<0',36,'existing paid',furniture/equipment,3959,'<100',unemployed,4,'male single',none,...,'life insurance',30,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
994,'no checking',12,'existing paid','new car',2390,'no known savings','>=7',4,'male single',none,...,car,50,none,own,1,skilled,1,yes,yes,good
995,'no checking',12,'existing paid',furniture/equipment,1736,'<100','4<=X<7',3,'female div/dep/mar',none,...,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,'<0',30,'existing paid','used car',3857,'<100','1<=X<4',4,'male div/sep',none,...,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,'existing paid',radio/tv,804,'<100','>=7',4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,'<0',45,'existing paid',radio/tv,1845,'<100','1<=X<4',4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,'0<=X<200',45,'critical/other existing credit','used car',4576,'100<=X<500',unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

## Goal:
We will learn and compare predictors for the class attribute (will a person get a credit or not). We will do this step-by-step

## Data exploration:
How many features and instances does this dataset have? What is the distribution of the target class?

## Create a numpy array for the target class
Remember that the array should contain only 1 and 0

## Create the numpy arrays of feature values
Split categorical variables into binary ones!

## Split the data randomly into 50% training and 50% test data

## Learn a Random Forest classifier on the training data

## Predict the class labels for the test dataset
Predict either absolute (1 or 0) or as probabilities

## Which features to influence the  classifier most?

## What is the accuracy of this classifier on the _Training Data_?

## What is the accuracy of this classifier on the _Test Data_?

## What is the mean 10-fold cross-validated accuracy of this classifier?

## How long did the cross-validation take?

## Compare this with a variety of other classifiers of your choice

# Congressional Data:
This data set includes votes for each of the U.S. House of Representatives Congressmen on the 16 key votes identified by the CQA. The CQA lists nine different types of votes: voted for, paired for, and announced for (these three simplified to yea), voted against, paired against, and announced against (these three simplified to nay), voted present, voted present to avoid conflict of interest, and did not vote or otherwise make a position known (these three simplified to an unknown disposition).

Source: https://archive.ics.uci.edu/ml/datasets/congressional+voting+records

Task: Build a classifier that can predict the party of a congress member based on his decision. use the last 50 instances of the dataset as a test set

In [4]:
df = pd.read_csv ("data/vote.csv", na_values="?")
df

,party,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y
5,democrat,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
6,democrat,n,y,n,y,y,y,n,n,n,n,n,n,NaN,y,y,y
7,republican,n,y,n,y,y,y,n,n,n,n,n,n,y,y,NaN,y
8,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
9,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,NaN,NaN
10,republican,n,y,n,y,y,n,n,n,n,n,NaN,NaN,y,y,n,n
11,republican,n,y,n,y,y,y,n,n,n,n,y,NaN,y,y,NaN,NaN
12,democrat,n,y,y,n,n,n,y,y,y,n,n,n,y,n,NaN,NaN
13,democrat,y,y,y,n,n,y,y,y,NaN,y,y,NaN,n,n,y,NaN
14,republican,n,y,n,y,y,y,n,n,n,n,n,y,NaN,NaN,n,NaN
15,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,NaN,n,NaN
16,democrat,y,n,y,n,n,y,n,y,NaN,y,y,y,NaN,n,n,y
17,democrat,y,NaN,y,n,n,n,y,y,y,n,n,n,y,n,y,y
18,republican,n,y,n,y,y,y,n,n,n,n,n,NaN,y,y,n,n
19,democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
20,democrat,y,y,y,n,n,NaN,y,y,n,n,y,n,n,n,y,y
21,democrat,y,y,y,n,n,n,y,y,y,n,n,n,NaN,NaN,y,y
22,democrat,y,NaN,y,n,n,n,y,y,y,n,n,NaN,n,n,y,y
23,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
24,democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,NaN
25,democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
26,democrat,y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y
27,democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
28,republican,y,n,n,y,y,n,y,y,y,n,n,y,y,y,n,y
29,democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,y
406,democrat,y,n,y,n,y,y,n,n,y,y,n,n,y,y,n,y
407,democrat,n,n,n,y,y,y,n,n,n,n,y,y,y,y,n,n
408,democrat,y,n,y,n,n,y,y,y,y,n,n,y,NaN,y,y,y
409,republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
410,republican,n,n,n,y,y,y,n,n,n,n,y,y,y,y,n,y
411,democrat,y,n,y,n,n,y,y,y,y,y,y,n,n,n,n,y
412,republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,y
413,republican,y,y,y,y,y,y,y,y,n,y,NaN,NaN,NaN,y,n,y
414,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,n,y
415,democrat,n,y,y,n,n,y,y,y,NaN,y,n,n,n,n,n,y
416,republican,y,y,n,y,y,y,n,n,n,y,n,n,y,y,n,y
417,democrat,y,y,y,n,n,n,y,y,y,y,y,n,y,n,n,y
418,democrat,y,y,y,n,n,n,y,y,n,y,n,n,n,n,n,y
419,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,n,y
420,republican,y,y,y,y,y,y,y,y,n,y,n,n,y,y,n,y
421,democrat,n,y,y,n,y,y,y,y,n,n,y,n,y,n,y,y
422,democrat,n,n,y,n,n,y,y,y,y,n,y,n,n,n,y,y
423,democrat,n,y,y,n,n,y,y,y,y,n,y,n,n,y,y,y
424,democrat,n,y,y,n,n,NaN,y,y,y,y,y,n,NaN,y,y,y
425,democrat,n,n,y,n,n,n,y,y,n,y,y,n,n,n,y,NaN
426,democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
427,republican,n,n,n,y,y,y,y,y,n,y,n,y,y,y,n,y
428,democrat,NaN,NaN,NaN,n,n,n,y,y,y,y,n,n,y,n,y,y
429,democrat,y,n,y,n,NaN,n,y,y,y,y,n,y,n,NaN,y,y
430,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
431,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
432,republican,n,NaN,n,y,y,y,n,n,n,n,y,y,y,y,n,y
433,republican,n,n,n,y,y,y,NaN,NaN,NaN,NaN,n,y,y,y,n,y
434,republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,NaN,n